### ISSUE TITLE
Error: The "@angular/compiler-cli" package was not properly installed.

### ISSUE THREAD

**Issue by mmc41** [arranbartish/angular-cli-seed#47]
Just tried a git clone + npm install + npm run test and got 

```
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/Users/xxx/temp/angular-cli-seed/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mmc/temp/angular-cli-seed/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**Comment by arranbartish** [comment]
Thanks for raising an issue. 

It looks like the travis build is doing exactly thatish. 

# travis.yml fragment
```
install:
  - npm install
  - npm install codecov
script:
  - npm run ng test -- --single-run=true --browsers Chrome --code-coverage
  - ./node_modules/codecov/bin/codecov
  - npm run e2e
  - npm run lint
  - npm run build
```

Except for the `codecov` that I am adding on the fly it should be the same. I'll clean clone and confirm on my machine. At the same time I'll rerun the travis build, it doesn't seem to have run in a while. 

What versions of `node` and `npm` are you running?

**Comment by arranbartish** [comment]
[travis][travis-build] agrees that the build is broken. It looks like some dependencies have changed/moved along. First thing that i'll do it lock them down to the versions that worked then see what I can do to upgrade

[travis-build]: https://travis-ci.org/arranbartish/angular-cli-seed/builds/228362896 "broken master"

**Comment by mmc41** [comment]
Thanks for looking at this. I am using npm 4.2.0 on node 7.9

**Comment by arranbartish** [comment]
Not forgotten this. A bit swamped for capacity right now, however there seems to be approaches to get back to green. 

1. lock down dependencies to those that were green
    - I tried this with the project dependencies, but have the same issues. It seems to be a dependency of a dependency that's moved on and caused the break.
2. Head down the upgrade path and fix any breaking issues

Any PR's for either are most welcome.
